INSERT INTO MEDICO VALUES (SEQ_MEDICO.NEXTVAL, 111111111111, 'RODRIGO', 'PEREZ');
INSERT INTO MEDICO VALUES (SEQ_MEDICO.NEXTVAL, 222222222222, 'RENATO', 'GALVEZ');
INSERT INTO MEDICO VALUES (SEQ_MEDICO.NEXTVAL, 333333333333, 'ACUÑA', 'EMILIO');

INSERT INTO PACIENTE VALUES (SEQ_PACIENTE.NEXTVAL, 'CAYO', 'JOSE HIGINIO 300 AÑO NUEVO COMAS LIMA', '74642154', 'JOSE LUIS EDUARDO', '988012997');
INSERT INTO PACIENTE VALUES (SEQ_PACIENTE.NEXTVAL, 'GUTIERRES', 'JR QUEMANA 234 AÑO NUEVO COMAS LIMA', '74854789', 'ALAN', '977454789');
INSERT INTO PACIENTE VALUES (SEQ_PACIENTE.NEXTVAL, 'GAMARRA', 'AV TUPAC AMARU 302 CARABAYLLO LIMA', '74574789', 'SINTHYA', '955545875');

INSERT INTO ESPECIALIDAD VALUES (SEQ_ESPECIALIDAD.NEXTVAL, 'NEUROLOGIA');
INSERT INTO ESPECIALIDAD VALUES (SEQ_ESPECIALIDAD.NEXTVAL, 'NEUMOLOGIA');
INSERT INTO ESPECIALIDAD VALUES (SEQ_ESPECIALIDAD.NEXTVAL, 'CIRUGIA GENERAL');
INSERT INTO ESPECIALIDAD VALUES (SEQ_ESPECIALIDAD.NEXTVAL, 'ODONTOLOGIA');

INSERT INTO EXAMEN VALUES (SEQ_EXAMEN.NEXTVAL, 'RADIOGRAFIA 3F1, TORAX 1/2', 'RADIOGRAFIA TORAX');
INSERT INTO EXAMEN VALUES (SEQ_EXAMEN.NEXTVAL, 'CIRUGIA EXPLORATORIA GASTROROLOGIA ORDINARIA', 'CIRUGIA EXPLORATORIA GASTROROLOGIA');
INSERT INTO EXAMEN VALUES (SEQ_EXAMEN.NEXTVAL, 'EXAMEN DE ORINA MRD 1/3', 'EXAMEN DE ORINA ORDINARIO');

COMMIT;
SELECT* FROM EXAMEN;

